version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: Europe/London

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: Europe/London
    ignore:
      - dependency-name: org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom
      - dependency-name: 'org.jetbrains.kotlinx:kotlinx-coroutines-bom'
        update-types: [ 'version-update:semver-minor' ]
      - dependency-name: 'org.jetbrains.kotlinx:kotlinx-serialization-bom'
        update-types: [ 'version-update:semver-minor' ]
    groups:
      kotlin:
        patterns:
          - "jvm"
          - "js"
          - "plugin.serialization"
        update-types:
          - minor

  - package-ecosystem: "npm"
    directory: "/kotlin-js-store"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: Europe/London
