name: "Example"
on: [push]

permissions:
  contents: read
  actions: write

jobs:
  prune-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Prune artifacts
        uses: araqnid/prune-artifacts@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
