name: "Gradle Build"
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.github/dependabot.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Remove .nvmrc
        run: rm -fv .nvmrc

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Compare dist with repo
        if: github.ref == 'refs/heads/main'
        run: |
          git diff --exit-code dist
